version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      # - checkout
      # - run:
      #     command:  |
      #       aws ec2 create-default-vpc
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
                --template-file template.yml \
                --stack-name stack
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
