version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
                --template-file template.yml \
                --parameters vpc.json \
                --stack-name my-staaaasck
workflows:
  my_workflow:
    jobs:
      - create_infrastructure